# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff416db36bd7f153b3795269f6a32e458154ed4e47cc0042a03f5c522e5e6fbc579cd5b3051fc17d33cc8bccc91a923922994b48b0574e60b244a77b3081e49

test:
  secret_key_base: 75293325d1a5f80b48faceaeb99919426b5a9beecb24159747934b0a1888b66aa34ad27045344a1d50f14d6ce5a4c162dc5da2159efc766636d4d15d60005cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
